# Goreleaser configuration for Port CLI

project_name: port-cli

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - id: port-cli
    binary: port
    main: ./cmd/port
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
      - -X 'main.buildDate={{.Date}}'
      - -X 'main.commit={{.Commit}}'
    env:
      - CGO_ENABLED=0
    buildmode: pie

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: port-experimental
    name: port-cli
  draft: false
